Nicer error when problem in install_requires
Instead of:

    $ python setup.py egg_info
    error in adminweb setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

We now have the more helpful:

    $ python setup.py egg_info
    error in adminweb setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers.
    Error: Expected version spec in smsdk.authsvc>=0.0.8,2.0 at 2.0

It took me longer than it should to find the problem with the old error
message. The new error message would've helped greatly.