Fix typo `find_namespaces:` to `find_namespace:`
I believe the correct `setup.cfg` packaging option is `find_namespace:`, not `find_namespaces:`
I can't find any other references to `find_namespaces` in the docs or repository.

Using `find_namespaces:` causes packaging to fail. Example to reproduce:
```
.
├── pyproject.toml
├── setup.cfg
└── src
    ├── pkg1
    │   └── namespace
    │       └── __init__.py
    └── pkg2
        └── __init__.py
```

Contents of `pyproject.toml`:
```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

Contents of `setup.cfg`:
```
[metadata]
name = pkg_test

[options]
packages = find_namespaces:
package_dir =
    =src

[options.packages.find]
where = src
```

```
$ pip install .
> ...
> error: package directory 'src/find_namespaces:' does not exist
> ...
```