Fix TypeError for pytest.skip()
pytests skip() method doesn't have a 'reason' parameter.
This fixes:

  TypeError: skip() got an unexpected keyword argument 'reason'

--HG--
branch : fix-type-error-skip-reason