build_meta: produce informative error when a dist is not found
Previously, when `build_sdist` or `build_wheel` were unable
to build a distribution (and were therefore unable to find the
distribution file), they would throw a

    ValueError: not enough values to unpack (expected 1, got 0)

which did not offer any clues as to where the issue might lie.